export const CONTENT = {
  profile: {
    name: "Otávio Monteiro",
    title: "Preparador Físico",
    bio: "Medicina na performance e na família",
    education: "Educação Física pela UNICESUMAR",
    cref: "[CONFIRMAR INFORMAÇÃO]",
    whatsapp: "5500000000000", // [CONFIRMAR INFORMAÇÃO]
    instagram: "https://www.instagram.com/otaviomonteiro.preparador/",
    location: "[CIDADE / REGIÃO DE ATENDIMENTO]",
  },
  hero: {
    title: "Prepare seu corpo para alcançar seu próximo nível.",
    subtitle: "Treinamento inteligente para performance e evolução individual e familiar.",
    ctaPrimary: "Agendar avaliação",
    ctaSecondary: "Conhecer o acompanhamento",
  },
  identification: {
    title: "O que você busca neste momento?",
    options: [
      { id: "conditioning", label: "Melhorar o condicionamento", icon: "Activity" },
      { id: "strength", label: "Ganhar força", icon: "Dumbbell" },
      { id: "performance", label: "Melhorar desempenho esportivo", icon: "Trophy" },
      { id: "return", label: "Retomar a atividade física", icon: "RefreshCw" },
      { id: "routine", label: "Criar uma rotina mais ativa", icon: "Calendar" },
      { id: "coaching", label: "Treinar com acompanhamento", icon: "Users" },
      { id: "challenge", label: "Preparar-se para um desafio", icon: "Mountain" },
      { id: "family", label: "Cuidar da performance da família", icon: "Heart" },
      { id: "unknown", label: "Ainda não sei qual caminho escolher", icon: "HelpCircle" },
    ],
  },
  modalities: [
    {
      id: "individual",
      name: "Treinamento Individual",
      forWhom: "Pessoas que buscam máxima personalização e atenção aos detalhes.",
      howItWorks: "Sessões presenciais ou acompanhamento direto focado em seus limites e objetivos.",
      benefit: "Evolução acelerada com técnica apurada.",
      frequency: "[CONFIRMAR INFORMAÇÃO]",
      format: "Presencial [CONFIRMAR]",
      cta: "Quero saber mais",
    },
    {
      id: "performance",
      name: "Preparação Física",
      forWhom: "Atletas amadores e profissionais em busca de ganho de performance específica.",
      howItWorks: "Planejamento estruturado baseado em demandas fisiológicas e biomecânicas.",
      benefit: "Aumento de potência e redução de riscos de lesão.",
      frequency: "[CONFIRMAR INFORMAÇÃO]",
      format: "Presencial/Híbrido [CONFIRMAR]",
      cta: "Quero saber mais",
    },
    {
      id: "online",
      name: "Consultoria Online",
      forWhom: "Pessoas que precisam de flexibilidade sem abrir mão de um plano profissional.",
      howItWorks: "Treinos entregues via plataforma com suporte direto para dúvidas e ajustes.",
      benefit: "Liberdade de horário com orientação de especialista.",
      frequency: "[CONFIRMAR INFORMAÇÃO]",
      format: "Digital",
      cta: "Quero saber mais",
    },
    {
      id: "family",
      name: "Acompanhamento Familiar",
      forWhom: "Famílias que desejam construir um estilo de vida ativo juntas.",
      howItWorks: "Atividades adaptadas para diferentes idades, promovendo saúde em conjunto.",
      benefit: "Fortalecimento de laços através do movimento.",
      frequency: "[CONFIRMAR INFORMAÇÃO]",
      format: "Presencial [CONFIRMAR]",
      cta: "Quero saber mais",
    },
  ],
  method: [
    { step: 1, title: "Conversa inicial", description: "Entendimento profundo de seus objetivos e restrições." },
    { step: 2, title: "Entendimento do objetivo", description: "Definição de metas claras e prazos realistas." },
    { step: 3, title: "Avaliação do nível atual", description: "Análise de movimento e capacidades físicas." },
    { step: 4, title: "Definição do plano", description: "Criação do cronograma e metodologia de treino." },
    { step: 5, title: "Orientação dos treinos", description: "Execução acompanhada ou suporte remoto constante." },
    { step: 6, title: "Acompanhamento da evolução", description: "Monitoramento de métricas e feedback." },
    { step: 7, title: "Ajustes periódicos", description: "Refinamento do plano conforme sua evolução." },
    { step: 8, title: "Reavaliação", description: "Análise de resultados para novos desafios." },
  ],
  faq: [
    {
      question: "Como funciona o acompanhamento?",
      answer: "O acompanhamento é baseado em um planejamento individualizado que considera seus objetivos, rotina e nível atual. [CONFIRMAR DETALHES]",
    },
    {
      question: "O atendimento é presencial ou online?",
      answer: "Oferecemos ambas as modalidades, dependendo da sua necessidade e localização. [CONFIRMAR DISPONIBILIDADE EM CIDADE]",
    },
    {
      question: "Para quem é a preparação física?",
      answer: "Para qualquer pessoa que queira sair do sedentarismo ou atletas que buscam otimizar seus resultados esportivos.",
    },
    {
      question: "É possível treinar em família?",
      answer: "Sim, temos programas específicos para integrar a rotina saudável no ambiente familiar.",
    },
    {
      question: "O acompanhamento substitui consulta médica?",
      answer: "Não. O trabalho de preparação física é complementar e focado em movimento e performance. Sempre recomendamos avaliação médica prévia.",
    },
  ],
};
